export const SEARCH_FETCH_TRIGGER = 'SEARCH_FETCH_TRIGGER';

export const SEARCH_FETCH_REQUEST = 'SEARCH_FETCH_REQUEST';

export const SEARCH_FETCH_SUCCESS = 'SEARCH_FETCH_SUCCESS';

export const SEARCH_FETCH_FAILURE = 'SEARCH_FETCH_FAILURE';

export const TOGGLE_DATA = 'TOGGLE_DATA';

export const CLEAR_SHOW = 'CLEAR_SHOW';

export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
