export const ADDRESS_FETCH_TRIGGER = 'ADDRESS_FETCH_TRIGGER';

export const ADDRESS_FETCH_REQUEST = 'ADDRESS_FETCH_REQUEST';

export const ADDRESS_FETCH_SUCCESS = 'ADDRESS_FETCH_SUCCESS';

export const LOADING_OFF = 'LOADING_OFF';
